name: azure_ad_oauth
description: Flutter Azure AD oAuth.
version: 0.0.1-dev.2

repository: https://github.com/13302296C/azure_ad_oauth
issue_tracker: https://github.com/13302296C/azure_ad_oauth/issues
homepage: https://github.com/13302296C/azure_ad_oauth
documentation: https://github.com/13302296C/azure_ad_oauth/blob/master/README.md

platforms:
  android:
  ios:
  web:

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: 
  shared_preferences:
  flutter_secure_storage:
  webview_flutter: ^4.0.0
  pedantic:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

